### ISSUE TITLE
`import fst` fails after `pip-3.2 install pyfst` with MacPorts

### ISSUE THREAD

**Issue by lebigot** [vchahun/pyfst#6]
`import fst` after `pip-3.2 install pyfst` (through MacPorts on OS X) fails with:

``` python
Python 3.2.3 (default, Apr 19 2012, 17:51:27) 
[GCC 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2335.15.00)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import fst
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.2/lib/python3.2/site-packages/fst/__init__.py", line 1, in <module>
    from fst._fst import EPSILON, EPSILON_ID, SymbolTable,\
  File "_fst.pyx", line 1, in init fst._fst (fst/_fst.cpp:27271)
NameError: basestring
```

Many warnings are issued during the compilation, most of them being related to a comparison between signed and unsigned variables, if this can help.

**Comment by vchahun** [comment]
There might still be subtle issues with unicode, but installation should work now.

**Comment by lebigot** [comment]
`import fst` now works inside MacPorts' Python 3.2. Thank you so much!
